### ISSUE TITLE
Didn't show up in chat.openai.com UI

### ISSUE THREAD

**Issue by DorianVasco** [polywock/gpt-search#3]
I use the addon with Firefox 123.0.1, the setting "always allow access to chat.openai.com" is checked. I also tried to disable uBlock Origin.

The search field does not show up at all on the website. Can I provide you with more information to debug?

**Comment by polywock** [comment]
Sure, but let's try the installation once more. If it didn't work again, could you also tell me your OS? 

1. Uninstall and re-install. 
2. Go to chat.openai.com, and what there, enable the permission from the menu. 

![firefox](https://github.com/polywock/gptSearch/assets/31208859/653359ae-4577-4333-b405-c1ec6df828a8)

**Comment by DorianVasco** [comment]
I did exactly as you described, but still no search. I have Windows 11. Tried it on two machines.

**Comment by DorianVasco** [comment]
I did exactly as you described, but still no search. I have Windows 11 and tried it on two machines.

**Comment by polywock** [comment]
Interesting. A few thoughts. 
1. I can confirm it works on Firefox 124 (Mac) and Firefox 123 (Linux) 
2. From the Firefox store dashboard, it looks like about 18 users (60% of all Firefox users) are on Windows with 123.0 being most common. The uninstall rate appears to be low, but there's not enough users to be sure. 

If you're willing can you try this version out? It's the same thing but opens prompt saying "Test" to check if the script loads. 

[packed.zip](https://github.com/polywock/gptSearch/files/14624976/packed.zip)

1. Open about:addons
2. Uninstall GPT Search
3. Click gear icon and select Debug Add-ons 
4. Click Load Temporary Add-Ons and select packed.zip 
5. Go to chat.openai.com, and while there, enable the permission from the menu.
6. Refresh the page. 

Does it say "Test"?

**Comment by DorianVasco** [comment]
Weirdly, your packed zip file worked fine including the popup. After reinstalled the version from the mozilla extensions, it again was not visible.

**Comment by polywock** [comment]
An update: Still no solution. From my testing, it seems to always work. It's weird that the packed version seems to work for you. The only thing different is that it's manually loaded instead of through the Firefox store. 

Here's the updated packed version. If you can't find an alternative addon that works, you can load this manually when you need it. 

[packed.zip](https://github.com/polywock/gpt-search/files/14913041/packed.zip)
