### ISSUE TITLE
Addon work only in Englis language

### ISSUE THREAD

**Issue by geek111** [polywock/gpt-search#5]
Hi,
this addon only load in english version chatgpt.com if you change language to anotther then cam't load.
It is option to change this to working on every language?

**Comment by polywock** [comment]
Can you explain a bit more? I tried changing the language to Turkish, Russian, French, etc and still seems to work fine.

**Comment by geek111** [comment]
Try Polish language.

**Comment by polywock** [comment]
No issue with Polish as well. There's probably another, unrelated cause.
