### ISSUE TITLE
Can't install GPT Search in MS Edge

### ISSUE THREAD

**Issue by cecilyen** [polywock/gpt-search#7]
Hi polywock,

I attempted to install your GPT Search extension from the Edge Add-ons store (https://microsoftedge.microsoft.com/addons/detail/gpt-search/hcnfioacjbamffbgigbjpdlflnlpaole), but encountered the following error:
Package is invalid. Details: 'Couldn't load icon 128.png specified in icons.'.

System Details:
macOS 14.6.1 (x86)
Edge 128.0.2739.42 (x86)

Could you please advise on how to resolve this issue?

Thanks!

**Comment by polywock** [comment]
Hello. I also get that error when trying to install. Not sure exactly why, so I'll just try republishing for now.  A similar issue happened a year or so back with another extension of mine. Republishing fixed the issue last time, and hopefully this time as well. It'll probably take 4-7 days to get approved. 

If you prefer not waiting, here's the unpacked version for now. 

[packed.zip](https://github.com/user-attachments/files/16801453/packed.zip)

1. Open edge://extensions
3. On the left side of the page, enable "Developer mode". 
4. On top right of page, click "Load unpacked" and select the folder (extract packed.zip first).

**Comment by polywock** [comment]
@cecilyen The update got approved pretty quickly this time. Installing for Microsoft Edge should now work.

**Comment by cecilyen** [comment]
It's working now. Thank you!
